version: '3.7'
services:


  sprout-server:
    image: savantly/franchise-manager-demo:latest
    container_name: fmgr-sprout-server
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER_CLASS: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  webapp:
    image: savantly/sprout-webapp
    container_name: fmgr-sprout-webapp
    ports:
      - 3000:3000
    environment: 
      - SPROUT_API_URL=http://fmgr-sprout-server:8080
    depends_on: 
      - sprout-server

  db:
    image: postgres
    container_name: fmgr-sprout-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    container_name: fmgr-sprout-adminer
    restart: always
    ports:
      - 8081:8080