version: '3.7'
services:

  webapp:
    image: savantly/sprout-webapp
    container_name: fmgr-sprout-webapp
    restart: always
    ports:
      - 3000:3000
    environment: 
      - SPROUT_API_URL=${SPROUT_API_URL:-http://host.docker.internal:8080}
    depends_on: 
      - sprout-server

  db:
    image: postgres
    container_name: fmgr-sprout-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=sprout
      - POSTGRES_PASSWORD=sprout
      - POSTGRES_USER=sprout

  adminer:
    image: adminer
    container_name: fmgr-sprout-adminer
    restart: always
    ports:
      - 8081:8080
