version: '3.7'
services:

  webapp:
    image: savantly/sprout-webapp
    container_name: fmgr-sprout-webapp
    restart: on-failure
    init: true
    ports:
      - ${WEB_PORT:-3000}:3000
    environment:
      SPROUT_API_URL: ${SPROUT_API_URL:-http://host.docker.internal:8080}

  db:
    image: postgres
    container_name: fmgr-sprout-db
    restart: on-failure
    init: true
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  adminer:
    image: adminer
    container_name: fmgr-sprout-adminer
    restart: on-failure
    init: true
    ports:
      - ${ADMINER_PORT:-8081}:8080

