name: Publish packages on release

# Suppress Spinner because it appears as warnings
env:
  SUPPRESS_SPINNER: true

on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      - name: GPG user IDs
        run: |
          echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
          echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
          echo "name:        ${{ steps.import_gpg.outputs.name }}"
          echo "email:       ${{ steps.import_gpg.outputs.email }}"

      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2.2.0
        with:
          java-version: 11

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Cache Gradle deps
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Module
        run: ./gradlew :fm-module:build

      - name: Publish java packages
        run: ./gradlew :fm-module:uploadArchives
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_USER_TOKEN: ${{ secrets.OSSRH_USER_TOKEN }}
